on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:

jobs:
  leetcode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: xqm32/xqm32.github.io
          token: ${{ secrets.LEETCODE }}
          path: blog
      - name: Setup Git
        run: |
          git config --global user.email "458173774@qq.com"
          git config --global user.name "Qiming Xu"
      - name: Commit blog
        run: |
          echo y | python lcmd.py leetcode.json
      - name: Commit leetcode
        run: |
          git add .
          git commit -m "leetcode: $(date -I)"
          git push
