on:
  workflow_dispatch:

jobs:
  leetcode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Commit leetcode
        run: |
          mv $(date +%Y.%-m.%d).* leetcode
          git add .
          git commit -m "leetcode: $(date -I)"
          git push
