on:
  workflow_dispatch:

jobs:
  leetcode:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Commit leetcode
        run: |
          git config --global user.email "33349132+xqm32@users.noreply.github.com"
          git config --global user.name "Qiming Xu"
          mv $(date +%Y.%-m.%-d).* leetcode
          git add .
          git commit -m "leetcode: $(date -I)"
          git push
